// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieDatabase", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("info");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Horror",
                            Director = "Guard",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Univited",
                            Year = 2009
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Fantasy",
                            Director = "Alfonso Cuaron",
                            Edited = false,
                            Rating = "PG",
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            Year = 2004
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Chick Flick",
                            Director = "Robert Luketic",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Legally Blonde",
                            Year = 2001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
